### ISSUE TITLE
grffile does not work with LuaTeX any more

### ISSUE THREAD

**Issue by e-kwsm** [ho-tex/grffile#1]
## Brief outline of the bug
latex3/latex2e@7fae7e881c812e1073b57e735264282bf77d8d55 breaks backward-compatibility:  grffile does not work with LuaLaTeX, while it still works with pdfLaTeX and XeLaTeX.

## Minimal example showing the bug

```latex
\documentclass{article}
\usepackage{grffile}
\usepackage{graphicx}
\begin{document}
\includegraphics{example-image-a.pdf}
\end{document}
```

LuaLaTeX emits the following error:
```
(/opt/texlive/2019/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))

LaTeX Warning: File `example-image-a.pdf' not found on input line 5.

! error:  (file """example-image-a".pdf) (pdf backend): cannot find image file 
'"""example-image-a".pdf'
!  ==> Fatal error occurred, no output PDF file produced!
```

OTOH pdfLaTeX and XeLaTeX can find the image.

My environment:
- lualatex: 1.10.0 (TeX Live 2019)
- pdflatex: 3.14159265-2.6-1.40.20 (TeX Live 2019)
- xelatex: 3.14159265-2.6-0.999991 (TeX Live 2019)
- grffile: 2017/06/30 v1.18
- graphics:  2019/07/20 v1.3b

## Log file (required) and possibly PDF file  
[mwe.log](https://github.com/ho-tex/oberdiek/files/3696893/mwe.log)

**Comment by davidcarlisle** [comment]
grffile (and this issue) have now been split off from the oberdiek bundle.

grffile 2.0 has just been uploaded to CTAN  and by default just loads the standard graphicx package, all handling of multiple dots and spaces is now in the base latex code and should work as expected
with

`LaTeX2e <2019-10-01> patch level 2`
