### ISSUE TITLE
grffile.sty not found after update

### ISSUE THREAD

**Issue by Martin-42** [ho-tex/grffile#2]
Hallo,

after last update grffile.sty is not found by (lua)latex. In fact the file no longer exist. Install with tlmgr is not successful. I use macOS Catalina and texlive 2019 basic. Before the tex system was updated everything was fine. 

Thanks
Martin

---
tlmgr info --list grffile:

package:     grffile
[...]
installed:   Yes
revision:    52680
sizes:       
relocatable: No
cat-version: 2.0
cat-date:    2019-11-07 18:22:07 +0100
[...]
collection:  collection-latexextra
Included files, by type:

---
--> no output after "Included files, by type"

**Comment by davidcarlisle** [comment]
looks like a tlmgr packaging issue, I'll raise it on tl list, thanks

**Comment by davidcarlisle** [comment]
Reported to texlive, note the new grffile just loads graphicx by default so removing it from the document should work in almost all cases.

**Comment by Martin-42** [comment]
Thank you for the quick answer. The function of grffile is clear to me, i noticed the problem while  using emacs org mode. The exporter writes usepackage grffile in the output.
