### ISSUE TITLE
grffile option "space" not found after update

### ISSUE THREAD

**Issue by ioneater** [ho-tex/grffile#3]
Hi, 

after updating today I got the error message 
! LaTeX Error: Unknown option `space' for package `grffile'.

Minimal example: \documentclass{standalone}\usepackage[space]{grffile}\begin{document}\end{document}

cheers

**Comment by u-fischer** [comment]
You hopefully no longer need grffile with a current latex, so simply remove it.

**Comment by ioneater** [comment]
Thanks, good to know. 
I had to remove a few quotation marks from my paths but now it works without grffile.

**Comment by davidcarlisle** [comment]
while you can remove the package it would be better not to error on options in existing documents 

https://github.com/ho-tex/grffile/commit/6ea1ddaf3ba90e9c023f5ee4b33a592cc8dc959d

makes the new version silently accept any option

**Comment by ioneater** [comment]
thanks david. always good to keep backwards compatibility
